name       : libnvidia-container
version    : 1.0.2
release    : 3
source     :
    - git|https://github.com/NVIDIA/libnvidia-container : v1.0.2
license    : BSD-3-Clause
component  : programming.library
summary    : NVIDIA container runtime library
description: |
    The nvidia-container library provides an interface to configure GNU/Linux
    containers leveraging NVIDIA hardware. The implementation relies on several
    kernel subsystems and is designed to be agnostic of the container runtime.
networking : yes
ccache     : no
builddeps  :
    - pkgconfig(libcap)
    - pkgconfig(libelf)
    - pkgconfig(libseccomp)
build      : |
    %make WITH_LIBELF=yes
install    : |
    %make_install WITH_LIBELF=yes prefix=/usr

    rm -v $installdir/usr/include/nvidia-modprobe-utils.h
    rm -v $installdir/usr/include/pci-enum.h
    rm -v $installdir/usr/lib/lib*.a
