name       : libnvidia-container
version    : 1.0.6
release    : 4
source     :
    - git|https://github.com/NVIDIA/libnvidia-container : v1.0.6
    - https://github.com/NVIDIA/nvidia-modprobe/archive/396.51.tar.gz : 25bc6437a384be670e9fd76ac2e5b9753517e23eb16e7fa891b18537b70c4b20
license    : Apache-2.0
component  : programming.library
summary    : NVIDIA container runtime library
description: |
    The nvidia-container library provides an interface to configure GNU/Linux
    containers leveraging NVIDIA hardware. The implementation relies on several
    kernel subsystems and is designed to be agnostic of the container runtime.
environment: |
    export WITH_LIBELF=yes
    export WITH_TIRPC=yes
    export WITH_SECCOMP=yes
builddeps  :
    - pkgconfig(libcap)
    - pkgconfig(libelf)
    - pkgconfig(libseccomp)
    - pkgconfig(libtirpc)
setup      : |
    %patch -p1 < $pkgfiles/use_system_libtirpc.patch
    %patch -p1 < $pkgfiles/use_downloaded_nvidia_modprobe.patch

    export NVIDIA_MODPROBE_VERSION=396.51
    mkdir -p deps/src
    tar -zxvf $sources/*.tar.gz -C deps/src
build      : |
    %make
install    : |
    %make_install prefix=%PREFIX% libdir=%libdir%
    
    rm -v $installdir/usr/include/nvidia-modprobe-utils.h
    rm -v $installdir/usr/include/pci-enum.h
    rm -v $installdir/%libdir%/lib*.a
