name       : libnvidia-container
version    : 1.5.1
release    : 9
source     :
    - git|https://github.com/NVIDIA/libnvidia-container : v1.5.1
license    : Apache-2.0
component  : programming.library
networking : yes
summary    : NVIDIA container runtime library
description: |
    The nvidia-container library provides an interface to configure GNU/Linux containers leveraging NVIDIA hardware. The implementation relies on several kernel subsystems and is designed to be agnostic of the container runtime.
environment: |
    export WITH_LIBELF=yes
    export WITH_TIRPC=yes
    export WITH_SECCOMP=yes
builddeps  :
    - pkgconfig(libcap)
    - pkgconfig(libelf)
    - pkgconfig(libseccomp)
    - pkgconfig(libtirpc)
    - rpcsvc-proto-devel
setup      : |
    %patch -p1 < $pkgfiles/use_system_libtirpc.patch
build      : |
    %make
install    : |
    %make_install prefix=%PREFIX% libdir=%libdir%

    rm -v $installdir/usr/include/nvidia-modprobe-utils.h
    rm -v $installdir/usr/include/pci-enum.h
    rm -v $installdir/%libdir%/lib*.a
    rm -rv $installdir/usr/share
